"use client";
import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, ClipboardList, FileText, LoaderCircle, Plus, Trash2 } from "lucide-react";

type Severity = "ปกติ" | "ต้องติดตาม" | "เร่งด่วน" | "วิกฤต";
type Report = { id:string; createdAt:string; target:string; address:string; severity:Severity; summary:string; findings:Array<{severity:Exclude<Severity,"ปกติ">;title:string;evidence:string;action:string}>; checks:{dns:{status:"pass"|"not_applicable";addresses:string[]};ping:{status:"pass"|"fail";averageMs?:number;loss?:number};ports:Array<{port:number;status:"open"|"closed"}>} };
const services=[{port:80,label:"เว็บ HTTP (80)",standard:true},{port:443,label:"เว็บ HTTPS (443)",standard:true},{port:445,label:"File share (445)",standard:true},{port:3389,label:"Remote Desktop (3389)",standard:true},{port:5432,label:"PostgreSQL (5432)",standard:true},{port:3000,label:"Node.js / Next.js (3000)",standard:false}];
const names:Record<number,string>={80:"เว็บ HTTP",443:"เว็บ HTTPS",445:"File share",3389:"Remote Desktop",5432:"PostgreSQL",3000:"Node.js / Next.js"};
const formatDate=(value:string)=>new Intl.DateTimeFormat("th-TH",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value));

export function ReportWorkbench(){
 const [target,setTarget]=useState(""); const [ports,setPorts]=useState<number[]>(()=>services.filter(s=>s.standard).map(s=>s.port)); const [custom,setCustom]=useState(""); const [reports,setReports]=useState<Report[]>([]); const [selectedId,setSelectedId]=useState<string|null>(null); const [loading,setLoading]=useState(true); const [running,setRunning]=useState(false); const [error,setError]=useState("");
 const selected=useMemo(()=>reports.find(r=>r.id===selectedId)??null,[reports,selectedId]);
 useEffect(()=>{fetch("/api/it-support/inspection").then(r=>r.json()).then(({reports})=>{setReports(reports??[]);setSelectedId(reports?.[0]?.id??null)}).catch(()=>setError("โหลดประวัติรายงานไม่สำเร็จ")).finally(()=>setLoading(false))},[]);
 const toggle=(port:number)=>setPorts(current=>current.includes(port)?current.filter(p=>p!==port):[...current,port]);
 const add=()=>{const value=Number(custom);if(!Number.isInteger(value)||value<1||value>65535){setError("Port เพิ่มเติมต้องเป็นตัวเลข 1–65535");return}setPorts(current=>current.includes(value)?current:[...current,value]);setCustom("")};
 const inspect=async(e:React.FormEvent)=>{e.preventDefault();if(!target.trim()){setError("กรุณาระบุ IP หรือชื่อเครื่องของเซิร์ฟเวอร์");return}setRunning(true);setError("");try{const response=await fetch("/api/it-support/inspection",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({target:target.trim(),ports})});const result=await response.json();if(!response.ok)throw new Error(result.error??"ตรวจสอบไม่สำเร็จ");setReports(current=>[result.report,...current].slice(0,100));setSelectedId(result.report.id)}catch(cause){setError(cause instanceof Error?cause.message:"ตรวจสอบไม่สำเร็จ")}finally{setRunning(false)}};
 const remove=async(id:string)=>{const response=await fetch(`/api/it-support/inspection?id=${encodeURIComponent(id)}`,{method:"DELETE"});if(!response.ok){setError("ลบรายงานไม่สำเร็จ");return}const next=reports.filter(r=>r.id!==id);setReports(next);if(selectedId===id)setSelectedId(next[0]?.id??null)};
 return <div className="its-report-workbench"><section className="its-panel its-report-intro"><div><p className="its-kicker">ตรวจจากระบบ IT Support อัตโนมัติ</p><h2>ตรวจสอบเซิร์ฟเวอร์และสร้างรายงาน</h2><p className="its-helper">กรอกเพียง IP/ชื่อเครื่อง ระบบจะตรวจ Ping และ Port มาตรฐานให้ทันที</p></div><FileText aria-hidden size={34}/></section><div className="its-report-grid"><form className="its-panel its-report-form" onSubmit={inspect}><fieldset><legend>ปลายทางที่ต้องการตรวจ</legend><label>IP หรือชื่อเครื่องเซิร์ฟเวอร์ <b>*</b><input value={target} onChange={e=>setTarget(e.target.value)} placeholder="เช่น 192.168.100.112" autoComplete="off"/></label><small>ระบบตรวจได้เฉพาะ IPv4 ใน IT_SUPPORT_ALLOWED_NETWORKS เท่านั้น</small></fieldset><fieldset><legend>Port มาตรฐาน <small>(ระบบเลือกให้แล้ว)</small></legend><p className="its-field-help">Port ที่ปิดเป็นข้อมูลประกอบ เพราะแต่ละเซิร์ฟเวอร์เปิดบริการไม่เท่ากัน</p><div className="its-port-options">{services.map(s=><label key={s.port}><input type="checkbox" checked={ports.includes(s.port)} onChange={()=>toggle(s.port)}/>{s.label}</label>)}</div><div className="its-custom-port"><label>Port เพิ่มเติม<input type="number" value={custom} onChange={e=>setCustom(e.target.value)} placeholder="เช่น 8080"/></label><button type="button" onClick={add}><Plus aria-hidden size={16}/>เพิ่ม</button></div></fieldset>{error&&<p className="its-form-error" role="alert">{error}</p>}<button className="its-primary" disabled={running}>{running?<><LoaderCircle aria-hidden size={18} className="its-spin"/>กำลังตรวจสอบ…</>:<><ClipboardList aria-hidden size={18}/>ตรวจสอบและบันทึกรายงาน</>}</button></form><section className="its-panel its-report-output" aria-live="polite">{loading?<div className="its-empty"><LoaderCircle aria-hidden size={26} className="its-spin"/>กำลังโหลดรายงาน…</div>:selected?<ReportDetail report={selected}/>:<div className="its-empty"><FileText aria-hidden size={26}/><strong>ยังไม่มีรายงาน</strong><span>ระบุปลายทาง แล้วกดตรวจสอบเพื่อสร้างรายงานอัตโนมัติ</span></div>}</section></div><section className="its-panel its-report-history"><div className="its-panel-head"><div><p className="its-kicker">บันทึกบนเครื่องที่รัน IT Support</p><h2>ประวัติรายงาน</h2></div><span>{reports.length} รายงาน</span></div>{reports.length?<ul>{reports.map(r=><li key={r.id}><button type="button" className={selectedId===r.id?"active":""} onClick={()=>setSelectedId(r.id)}><span className={`its-report-level its-report-level-${r.severity}`}>{r.severity}</span><strong>{r.target}</strong><small>{r.address} · {formatDate(r.createdAt)}</small></button><button className="its-report-delete" type="button" onClick={()=>remove(r.id)} aria-label={`ลบรายงาน ${r.target}`}><Trash2 aria-hidden size={17}/></button></li>)}</ul>:<p className="its-empty">รายงานที่สร้างแล้วจะแสดงที่นี่</p>}</section></div>
}

function RemoteDesktopGuide({address}:{address:string}){return <div className="its-guide-start"><b>ก่อนเริ่ม: ต้องทำบนเครื่องเซิร์ฟเวอร์ ไม่ใช่คอมที่เปิด IT Support</b><span>หากยังไม่เห็นหน้า Desktop ของเซิร์ฟเวอร์ ให้เชื่อมต่อจากคอมของคุณตามลำดับนี้</span><ol className="its-rdp-steps"><li>กดปุ่ม <kbd>⊞ Windows</kbd> บนคีย์บอร์ด</li><li>พิมพ์ <kbd>Remote Desktop Connection</kbd> แล้วกด <kbd>Enter</kbd></li><li>ในช่อง <kbd>Computer</kbd> ให้ใส่ IP: <kbd>{address}</kbd> แล้วกด <kbd>Connect</kbd></li><li>เข้าสู่ระบบด้วยบัญชีที่ได้รับสิทธิ์ผู้ดูแลระบบ</li><li>เมื่อเห็นหน้า Desktop ของเซิร์ฟเวอร์แล้ว จึงทำขั้นตอนด้านล่างต่อ</li></ol></div>}
function ReportDetail({report}:{report:Report}){const closed=report.checks.ports.filter(p=>p.status==="closed");const open=report.checks.ports.filter(p=>p.status==="open").length;return <><div className="its-report-summary"><span className={`its-report-level its-report-level-${report.severity}`}>{report.severity}</span><div><p className="its-kicker">รายงานล่าสุด · {formatDate(report.createdAt)}</p><h2>{report.target}</h2><small>{report.address}</small></div></div><p className="its-helper">{report.summary}</p><dl className="its-auto-checks"><div><dt>DNS</dt><dd>{report.checks.dns.status==="not_applicable"?"ไม่ได้ตรวจ (ระบุ IP)":`ผ่าน · ${report.checks.dns.addresses.join(", ")}`}</dd></div><div><dt>Ping</dt><dd>{report.checks.ping.status==="pass"?`ผ่าน · ${report.checks.ping.averageMs??0} ms`:"ไม่ตอบกลับ"}</dd></div><div><dt>Port มาตรฐาน</dt><dd>{open} / {report.checks.ports.length} เปิด</dd></div></dl>{report.findings.length?<ol className="its-findings">{report.findings.map((f,i)=><li key={i}><AlertTriangle aria-hidden size={19}/><div><span className={`its-report-level its-report-level-${f.severity}`}>{f.severity}</span><strong>{f.title}</strong><p><b>ข้อมูลที่พบ:</b> {f.evidence}</p><p><b>แนะนำ:</b> {f.action}</p></div></li>)}</ol>:<div className="its-report-clean"><CheckCircle2 aria-hidden size={21}/>การเชื่อมต่อพื้นฐานผ่านแล้ว</div>}<div className="its-port-results">{report.checks.ports.map(p=><span key={p.port} className={p.status==="open"?"open":"closed"}>Port {p.port}: {p.status==="open"?"เปิด":"ปิด/ไม่ตอบ"}</span>)}</div>{closed.length>0&&<section className="its-remediation"><h3>Port ปิด: วิธีตรวจและแก้ไขทีละขั้น</h3>{closed.map(p=><details key={p.port}><summary>{names[p.port]??`Port ${p.port}`} · Port {p.port}<span>กดเพื่อดูทีละขั้น</span></summary><RemoteDesktopGuide address={report.address}/><ol><li>บน Desktop ของเซิร์ฟเวอร์ กด Start แล้วพิมพ์ <kbd>Services</kbd> จากนั้นกด Enter</li><li>ตรวจว่าโปรแกรมหรือบริการที่ใช้ Port {p.port} มี Status เป็น Running; หากหยุดอยู่ ให้คลิกขวาแล้วเลือก Start</li><li>เปิด Start &gt; Windows Defender Firewall with Advanced Security &gt; Inbound Rules แล้วตรวจหรือเพิ่มกฎ TCP สำหรับ Port {p.port}</li><li>กลับมาที่หน้านี้แล้วกดตรวจสอบซ้ำ หากยังปิด ให้ส่งข้อความ error ให้ผู้ดูแลระบบ</li></ol></details>)}</section>}</>}
