import type { DiagnosticResult, DnsResult, PingResult, PortResult } from "./types";
export interface NetworkService { ping(target: string): Promise<PingResult>; dnsLookup(domain: string): Promise<DnsResult>; checkPort(host: string, port: number): Promise<PortResult>; diagnose(target: string): Promise<DiagnosticResult>; }
const pause = () => new Promise((resolve) => setTimeout(resolve, 550));
export class MockNetworkService implements NetworkService {
  async ping(target: string): Promise<PingResult> { await pause(); const failed = target.toLowerCase().includes("fail"); return { target, address: target === "google.com" ? "142.250.72.14" : target, status: failed ? "offline" : "online", sent: 4, received: failed ? 0 : 4, loss: failed ? 100 : 0, average: failed ? 0 : 12, min: failed ? 0 : 8, max: failed ? 0 : 19 }; }
  async dnsLookup(domain: string): Promise<DnsResult> { await pause(); return { domain, responseTime: 18, records: [{ type: "A", value: "142.250.72.14" }, { type: "AAAA", value: "2404:6800:4003:c00::65" }, { type: "MX", value: "smtp.google.com (priority 10)" }, { type: "NS", value: "ns1.google.com" }, { type: "TXT", value: "v=spf1 include:_spf.google.com ~all" }] }; }
  async checkPort(host: string, port: number): Promise<PortResult> { await pause(); const open = [53, 80, 443, 445, 3389].includes(port); return { host, port, open, service: ({ 53: "DNS", 80: "HTTP", 443: "HTTPS", 445: "SMB", 3389: "RDP" } as Record<number, string>)[port] ?? "Unknown service", latency: open ? 7 : 0 }; }
  async diagnose(target: string): Promise<DiagnosticResult> { await pause(); return { target, steps: [{ id: "target", title: "Validate target", detail: target, status: "pass" }, { id: "adapter", title: "Network adapter", detail: "Ethernet 2 · Connected", status: "pass" }, { id: "ip", title: "IP address", detail: "192.168.10.25 / 24", status: "pass" }, { id: "gateway", title: "Gateway ping", detail: "192.168.10.1 · 3ms", status: "pass" }, { id: "internet", title: "Internet ping", detail: "8.8.8.8 · 12ms", status: "pass" }, { id: "dns", title: "DNS resolve", detail: "google.com did not resolve", status: "failed" }, { id: "target-check", title: "Check target", detail: "Waiting for DNS recovery", status: "pending" }, { id: "port", title: "Required port", detail: "Waiting for DNS recovery", status: "pending" }], diagnosis: "Possible DNS server problem", confidence: 92, commands: ["ipconfig /flushdns", "ipconfig /release", "ipconfig /renew", "nslookup google.com"] }; }
}
export const networkService = new MockNetworkService();
