import { execFile } from "node:child_process";
import { lookup, reverse } from "node:dns/promises";
import net from "node:net";
import os from "node:os";
import { promisify } from "node:util";
const executeFile = promisify(execFile);
type Severity = "ปกติ" | "ต้องติดตาม" | "เร่งด่วน" | "วิกฤต";
type Finding = { severity: Exclude<Severity, "ปกติ">; title: string; evidence: string; action: string };
export type InspectionReport = { id: string; createdAt: string; target: string; address: string; severity: Severity; summary: string; findings: Finding[]; checks: { dns: { status: "pass" | "not_applicable"; addresses: string[]; reverseName?: string }; ping: { status: "pass" | "fail"; averageMs?: number; loss?: number; detail: string }; ports: Array<{ port: number; status: "open" | "closed"; detail: string }> } };
function ipNumber(ip: string) { return ip.split(".").reduce((value, part) => (value * 256) + Number(part), 0) >>> 0; }
function validIpv4(ip: string) { const parts = ip.split("."); return parts.length === 4 && parts.every((part) => /^\d+$/.test(part) && Number(part) >= 0 && Number(part) <= 255); }
function inCidr(ip: string, range: string) { const [network, bitsText] = range.trim().split("/"); const bits = Number(bitsText); if (!validIpv4(ip) || !validIpv4(network) || !Number.isInteger(bits) || bits < 0 || bits > 32) return false; const mask = bits === 0 ? 0 : (0xffffffff << (32 - bits)) >>> 0; return (ipNumber(ip) & mask) === (ipNumber(network) & mask); }
function allowed(addresses: string[]) { const ranges = (process.env.IT_SUPPORT_ALLOWED_NETWORKS ?? "").split(",").map((value) => value.trim()).filter(Boolean); return Boolean(ranges.length) && addresses.every((address) => validIpv4(address) && ranges.some((range) => inCidr(address, range))); }
function requestedPorts(input: unknown) { return Array.isArray(input) ? [...new Set(input.map(Number))].filter((port) => Number.isInteger(port) && port >= 1 && port <= 65535).slice(0, 12) : []; }
async function ping(address: string) { const args = os.platform() === "win32" ? ["-n", "2", "-w", "1500", address] : ["-c", "2", "-W", "2", address]; try { const { stdout } = await executeFile("ping", args, { timeout: 4500, windowsHide: true, maxBuffer: 8192 }); const average = stdout.match(/(?:Average|avg)\s*[=:]\s*(\d+(?:\.\d+)?)\s*ms/i) ?? stdout.match(/=\s*[\d.]+\/[\d.]+\/([\d.]+)\//); const loss = stdout.match(/\((\d+(?:\.\d+)?)%\s*(?:loss|packet loss)\)/i) ?? stdout.match(/(\d+(?:\.\d+)?)%\s*packet loss/i); return { status: "pass" as const, averageMs: average ? Number(average[1]) : undefined, loss: loss ? Number(loss[1]) : 0, detail: "ปลายทางตอบกลับ Ping" }; } catch (error) { const detail = (error as { stdout?: string }).stdout?.trim() || "ปลายทางไม่ตอบกลับ Ping ภายในเวลาที่กำหนด"; return { status: "fail" as const, detail: detail.slice(0, 280) }; } }
function checkPort(address: string, port: number) { return new Promise<{ port: number; status: "open" | "closed"; detail: string }>((resolve) => { const socket = new net.Socket(); let complete = false; const finish = (status: "open" | "closed", detail: string) => { if (complete) return; complete = true; socket.destroy(); resolve({ port, status, detail }); }; socket.setTimeout(1800); socket.once("connect", () => finish("open", "เชื่อมต่อ TCP ได้")); socket.once("timeout", () => finish("closed", "หมดเวลารอการเชื่อมต่อ")); socket.once("error", (error) => finish("closed", (error as NodeJS.ErrnoException).code === "ECONNREFUSED" ? "ปลายทางปฏิเสธการเชื่อมต่อ" : "เชื่อมต่อไม่ได้")); socket.connect(port, address); }); }
const weight: Record<Severity, number> = { "ปกติ": 0, "ต้องติดตาม": 1, "เร่งด่วน": 2, "วิกฤต": 3 };
export async function inspectTarget(input: { target?: unknown; ports?: unknown }): Promise<InspectionReport> { const target = typeof input.target === "string" ? input.target.trim() : ""; if (!target || target.length > 253 || /[\s/\\]/.test(target)) throw new Error("กรุณาระบุ IP หรือชื่อเครื่องให้ถูกต้อง"); const isIp = validIpv4(target); const addresses = isIp ? [target] : (await lookup(target, { all: true, verbatim: true })).filter((item) => item.family === 4).map((item) => item.address); if (!addresses.length) throw new Error("ไม่พบ IPv4 ของปลายทาง"); if (!allowed(addresses)) throw new Error("ปลายทางอยู่นอกเครือข่ายที่อนุญาต โปรดตรวจ IT_SUPPORT_ALLOWED_NETWORKS"); const address = addresses[0]; const ports = requestedPorts(input.ports); const findings: Finding[] = []; const [pingResult, portResults, reverseResult] = await Promise.all([ping(address), Promise.all(ports.map((port) => checkPort(address, port))), isIp ? reverse(address).catch(() => []) : Promise.resolve([])]); if (pingResult.status === "fail") findings.push({ severity: "วิกฤต", title: "ปลายทางไม่ตอบสนองต่อ Ping", evidence: pingResult.detail, action: "ตรวจว่าเครื่องเปิดอยู่, ตรวจเส้นทางเครือข่าย และยืนยันว่า ICMP ไม่ถูก firewall ปิดกั้น" }); else if ((pingResult.loss ?? 0) >= 3) findings.push({ severity: "เร่งด่วน", title: "พบ packet loss", evidence: `Packet loss ${pingResult.loss}%`, action: "ตรวจสายสัญญาณ, switch และ interface error ก่อน" }); else if ((pingResult.averageMs ?? 0) >= 120) findings.push({ severity: "ต้องติดตาม", title: "Ping สูงกว่าปกติ", evidence: `Ping เฉลี่ย ${pingResult.averageMs} ms`, action: "ตรวจเส้นทางและปริมาณการใช้งานเครือข่ายในช่วงเวลาเดียวกัน" }); const severity = findings.reduce<Severity>((highest, finding) => weight[finding.severity] > weight[highest] ? finding.severity : highest, "ปกติ"); const openPorts = portResults.filter((item) => item.status === "open").length; const summary = findings.length ? `ตรวจพบ ${findings.length} ประเด็น ระดับสูงสุด: ${severity}` : ports.length ? `การเชื่อมต่อผ่าน · Port มาตรฐานเปิด ${openPorts}/${ports.length} รายการ (Port ที่ปิดอาจไม่จำเป็นต้องใช้งาน)` : "การเชื่อมต่อพื้นฐานผ่านแล้ว"; return { id: crypto.randomUUID(), createdAt: new Date().toISOString(), target, address, severity, summary, findings, checks: { dns: { status: isIp ? "not_applicable" : "pass", addresses, reverseName: reverseResult[0] }, ping: pingResult, ports: portResults } }; }
